# Generated by Django 4.0.4 on 2023-02-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=120, null=True)),
                ('size', models.CharField(max_length=3, null=True)),
                ('duration', models.CharField(max_length=2, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
